services:
  # Service pour l'application Next.js
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb+srv://axel:hoboujunior54@cluster0.sfbgeur.mongodb.net/my_rotten_db 
    depends_on:
      - mongo 

  # Service pour MongoDB
  mongo:
    image: mongo:latest # Utilise l'image officielle de MongoDB
    container_name: mongo_db
    ports:
      - "27018:27017" # Mappe le port 27017 de l'hôte au port 27017 du conteneur
    
    volumes:
      - mongo_data:/data/db # Persistance des données MongoDB

volumes:
  mongo_data: # Définit le volume pour la persistance des données